server:
  port: 8080
spring:
  profiles:
    include:
      - db
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
   #参数意义：
   #JsonInclude.Include.ALWAYS           默认的意思是即时属性为null，仍然也会输出这个key
   #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
   #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
   #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


#  jackson:
#    #日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization:
#      #格式化输出
#      indent_output: true
#      #忽略无法转换的对象
#      fail_on_empty_beans: false
#    #设置空如何序列化
#    defaultPropertyInclusion: NON_EMPTY
#    deserialization:
#      #允许对象忽略json中不存在的属性
#      fail_on_unknown_properties: false
#    parser:
#      #允许出现特殊字符和转义符
#      allow_unquoted_control_chars: true
#      #允许出现单引号
#      allow_single_quotes: true

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations:
    - classpath:mapper/*/*Mapper.xml
# log
logging:
  config: classpath:log4j2-console.xml